# export LOCAL_IP=$(ifconfig | grep -E 'inet |broadcast' | grep -Ev 'broadcast 0|127' | awk '{print $2}' | head -1)
version : '2'
services :

  px-lighthouse :
    image : portworx/px-lighthouse
    restart : always
    container_name : px-lighthouse
    network_mode : "bridge"
    volumes :
      - /var/log:/var/log
    ports :
      - "80:80"
    depends_on : 
      - influx-px
      - consul-px
    links :
      - influx-px
      - etcd-px
    environment :
      - PWX_INFLUXDB="http://influx-px:8086"
      - PWX_INFLUXUSR="admin"
      - PWX_INFLUXPW="password"
      - PWX_HOSTNAME=${LOCAL_IP}
    entrypoint :
      - /bin/bash
      - /lighthouse/on-prem-entrypoint.sh
      - -k
      - consul:http://${LOCAL_IP}:2379
      - -d
      - http://${PWX_INFLUXUSR}:${PWX_INFLUXPW}@${LOCAL_IP}:8086

  influx-px :
    image : tutum/influxdb
    restart : always
    container_name : influx-px
    network_mode : "bridge"
    ports :
      - "8083:8083"
      - "8086:8086"
    environment :
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - ADMIN_USER="admin" 
      - INFLUXDB_INIT_PWD="password" 
      - PRE_CREATE_DB="px_stats"

  consul-px :
    image : consul
    restart : always
    container_name : consul-px
    network_mode : "bridge"
    ports :
      - "8300:8300"
      - "8500:8500"
    volumes :
      - /tmp/consul:/consul/data
